{
  "openapi": "3.0.2",
  "info": {
    "title": "User API",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://localhost:8000",
      "description": "User API"
    }
  ],
  "paths": {
    "/api/users/register": {
      "description": "register new user",
      "post": {
        "description": "register new user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createOrUpdateUserReqBody"
              },
              "examples": {
                "aditya": {
                  "$ref": "#/components/examples/requestBody"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User Created",
            "content": {
              "application/json": {
                "examples": {
                  "aditya": {
                    "$ref": "#/components/examples/user"
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/GetUser"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "validation error": {
                    "value": {
                      "errors": {
                        "username": [
                          "username must not be blank",
                          "username min 6 characters"
                        ],
                        "email": [
                          "email must not be blank",
                          "email must contain @ and ."
                        ],
                        "password": [
                          "password must not be blank",
                          "password min 6 characters"
                        ],
                        "name": [
                          "name must not be blank",
                          "name min 6 characters"
                        ]
                      }
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "description": "login user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "username",
                  "password"
                ],
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "aditya": {
                  "description": "login with user aditya",
                  "value": {
                    "username": "aditya123",
                    "password": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "username": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "token": {
                          "type": "string"
                        }
                      }
                    },
                    "errors": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/current": {
      "get": {
        "description": "Get current user",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get current user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUser"
                },
                "examples": {
                  "aditya": {
                    "$ref": "#/components/examples/user"
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "Update current user",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ],
        "requestBody": {
          "description": "Update current user",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createOrUpdateUserReqBody"
              },
              "examples": {
                "aditya": {
                  "$ref": "#/components/examples/requestBody"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update current user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUser"
                },
                "examples": {
                  "aditya": {
                    "$ref": "#/components/examples/user"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "log out user",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        }
                      }
                    },
                    "errors": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "Authorization": {
        "in": "header",
        "name": "Authorization",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    },
    "schemas": {
      "GetUser": {
        "description": "User object",
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "username": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              }
            }
          },
          "errors": {
            "type": "object"
          }
        }
      },
      "createOrUpdateUserReqBody": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "user": {
        "value": {
          "data": {
            "id": 1,
            "username": "aditya123",
            "email": "aditya@tes.com",
            "name": "aditya"
          },
          "errors": {}
        }
      },
      "requestBody": {
        "value": {
          "username": "aditya123",
          "name": "aditya",
          "email": "aditya@tes.com",
          "password": "123456"
        }
      }
    }
  }
}